# carbon-tracker-frontend/Dockerfile.dev

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Expose the standard Vite port
EXPOSE 5173

# Start the app in development mode with --host to expose it to Docker
CMD ["npm", "run", "dev", "--", "--host"]