# Generated by Django 5.2.6 on 2025-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_activity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('co2e_per_unit', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
