# Generated by Django 5.2.6 on 2025-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emissionfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
