# Generated by Django 5.2.6 on 2025-10-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emissionfactor_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
