# Generated by Django 5.2.6 on 2025-12-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_activity_created_at_activity_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='distance',
            new_name='quantity',
        ),
    ]
