# Generated by Django 5.2.6 on 2026-02-28 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='source_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
