# Generated by Django 5.2.6 on 2026-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emissionfactor_added_by_emissionfactor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
