# Generated by Django 5.2.6 on 2026-02-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emissionfactor_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionfactor',
            old_name='is_verified',
            new_name='is_verified_factor',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
